### ISSUE TITLE
"New Search" and "Check for Updates" links are not working on CTS Print page on Blue 

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/clinical-trials-search-print#63]
### Issue description
"New Search" and "Check for Updates" links are not working on CTS Print page on Blue 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Click on Find Trails on Basic Search
2. Select a trial and Click Print selected button
3. Click on "New Search" link 
4. Click on "Check for Updates"

### What's the expected result?
-"New Search" should open Basic Search page
"Check for Updates" should open the Trial Description page

### What's the actual result?
-Blank Placeholder pages are displayed for both of them

### Additional details / screenshot
"New Search" : 
![image](https://user-images.githubusercontent.com/31008800/163260537-26805582-7c7d-4f7d-b563-08bbdcfd22ab.png)

- "Check for Updates" : 
![image](https://user-images.githubusercontent.com/31008800/163260390-afde5d90-9bc1-4e7f-80d5-7088ef1f967b.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment]
This happens because the search application is sending relative links to the trial detail and new search pages.  This is by design in order to prevent links to other sites from being injected.  (The search service will reject absolute links.)

The links being passed are structured correctly.  To test this on your local machine:

1. Perform a search (basic or advanced)
2. Select one or more trials
3. Click the  "Print Selected" button.
4. On the print page:
    1. Right-click the link (applies to both "Check for updates" and "New Search"
    2. Choose "Copy link address" (or the equivalent selection in your browser of choice)
    3. Open a new browser tab.
    4. Paste the link into the browser bar.
    5. Replace the `https:` with `http:`
    6. Replace `www-blue-dev.cancer.gov` with `localhost:3000` (That's the default port number for the trials application. If you're using a different one, make the appropriate substitution.)
    7. Press the `Enter` key to go to the new address.
